In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [40]:
snsMessages = pd.read_csv('spam.csv', encoding='latin-1')

In [42]:
snsMessages=snsMessages.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [46]:
snsMessages.rename(columns={'v1':'label','v2':'message'},inplace=True)

In [52]:
snsMessages['labelNumber']=snsMessages.label.map({'ham' : 0,'spam' : 1})

In [54]:
X=snsMessages.message
y=snsMessages.labelNumber

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=13)

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
vector=CountVectorizer()
vector.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [65]:
X_train_dtmatrix=vector.transform(X_train)

In [68]:
X_test_dtmatrix=vector.transform(X_test)

In [69]:
print(X_test_dtmatrix.shape)

(1672, 7250)


In [70]:
from sklearn.naive_bayes import MultinomialNB

In [71]:
nbModel=MultinomialNB()
nbModel.fit(X_train_dtmatrix,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [72]:
nbModelPrediction=nbModel.predict(X_test_dtmatrix)

In [73]:
from sklearn import metrics

In [74]:
modelAccuracy=metrics.accuracy_score(y_test , nbModelPrediction)

In [75]:
print(modelAccuracy)

0.9880382775119617


In [78]:
confusionMatrix = (metrics.confusion_matrix(y_test , nbModelPrediction))

In [79]:
print(confusionMatrix)

[[1436    5]
 [  15  216]]


In [80]:
from sklearn.linear_model import LogisticRegression

In [81]:
logModel=LogisticRegression()

In [82]:
logModel.fit(X_train_dtmatrix , y_train)

C:\Users\AAYUSH AGARWAL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [83]:
logModelPrediction=logModel.predict(X_test_dtmatrix)

In [84]:
logModelAccuracy=metrics.accuracy_score(y_test , logModelPrediction)

In [86]:
print(logModelAccuracy)

0.9826555023923444


In [87]:
logModelConfusionMatrix=metrics.confusion_matrix(y_test , logModelPrediction)

In [88]:
print(logModelConfusionMatrix)

[[1436    5]
 [  24  207]]


In [89]:
print(X_test[y_test < nbModelPrediction])

2418    Madam,regret disturbance.might receive a refer...
990                                          26th OF JULY
1259    We have sent JD for Customer Service cum Accou...
5044    We have sent JD for Customer Service cum Accou...
4555                              Gettin rdy to ship comp
Name: message, dtype: object


In [90]:
print(X_test[y_test > nbModelPrediction])

3417    LIFE has never been this much fun and great un...
3862    Oh my god! I've found your number again! I'm s...
683     Hi I'm sue. I am 20 years old and work as a la...
1499    SMS. ac JSco: Energy is high, but u may not kn...
4211    Missed call alert. These numbers called but le...
1892    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
2773    How come it takes so little time for a child w...
1268    Can U get 2 phone NOW? I wanna chat 2 set up m...
855     Talk sexy!! Make new friends or fall in love i...
1457    CLAIRE here am havin borin time & am now alone...
2662    Hello darling how are you today? I would love ...
4142    In The Simpsons Movie released in July 2007 na...
2574    Your next amazing xxx PICSFREE1 video will be ...
954             Filthy stories and GIRLS waiting for your
68      Did you hear about the new \Divorce Barbie\"? ...
Name: message, dtype: object


In [104]:
ar=nbModel.feature_count_
print(ar)

[[ 0.  0.  0. ...  1.  0.  8.]
 [ 7. 20.  2. ...  0.  1.  0.]]


In [95]:
X_train_words=vector.get_feature_names()

In [99]:
print(X_train_words[7000:7005])

['wherevr', 'wherre', 'whether', 'which', 'while']


In [102]:
hamWordCount=ar[0,:]
spamWordCount=ar[1,:]

In [103]:
print(hamWordCount)

[0. 0. 0. ... 1. 0. 8.]


In [105]:
tokens=pd.DataFrame({'token' : X_train_words , 'spam' : spamWordCount , 'ham' : hamWordCount})

In [106]:
tokens.head()

token  spam  ham
0            00   7.0  0.0
1           000  20.0  0.0
2  008704050406   2.0  0.0
3          0089   1.0  0.0
4          0121   1.0  0.0

In [107]:
tokens.tail()

token  spam  ham
7245        ó_   0.0  1.0
7246        û_   0.0  8.0
7247  û_thanks   0.0  1.0
7248      ûªve   1.0  0.0
7249        ûò   0.0  8.0

In [108]:
tokens=tokens.set_index('token')

In [109]:
tokens.head()

spam  ham
token                  
00             7.0  0.0
000           20.0  0.0
008704050406   2.0  0.0
0089           1.0  0.0
0121           1.0  0.0

In [110]:
nbModel.class_count_

array([3384.,  516.])